# Documentation: https://github.com/compose-spec/compose-spec/blob/master/spec.md
# Purpose: Build local containers for the Mutillidae environment

version: '3.7'
services:

  database:
    container_name: database
    image: docker.io/webpwnized/mutillidae:database
    ports:
      - 3306:3306
      - 33060:33060
    networks:
      - datanet   

  database_admin:
    container_name: database_admin
    depends_on:
      - database
    image: docker.io/webpwnized/mutillidae:database_admin
    ports:
      - 81:80
    networks:
      - datanet   

  # IP 127.0.0.1 is for mutillidae.localhost or www.mutillidae.localhost
  # IP 127.0.0.1 is for cors.mutilliiidae.localhost
  www:
    container_name: www
    depends_on:
      - database
      - directory
    image: docker.io/webpwnized/mutillidae:www
    ports:
      - 80:80
      - 443:443
      # - 127.0.0.2:80:80
      # - 127.0.0.2:443:443
    networks:
      - datanet
      - ldapnet

  directory:
    container_name: directory
    image: docker.io/webpwnized/mutillidae:ldap
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    ports:
      - 389:389
    networks:
      - ldapnet

  directory_admin:
    container_name: directory_admin
    depends_on:
      - directory
    image: docker.io/webpwnized/mutillidae:ldap_admin
    ports:
      - 82:80
    networks:
      - ldapnet

# Volumes to persist data used by the LDAP server
volumes:
  ldap_data:
  ldap_config:

# Create network segments for the containers to use
networks:
    datanet:
    ldapnet: