# -*- mode: ruby -*- 
# vi: set ft=ruby : 

ENV['VAGRANT_NO_PARALLEL'] = 'yes' 

Vagrant.configure(2) do |config| 

	config.vm.define "jasonlws-kali" do |kali| 

		kali.vm.hostname = "jasonlws-kali" 

		kali.vm.box = "kalilinux/rolling" 

		kali.vm.network "private_network", ip: "192.168.56.110", netmask: "255.255.255.0"

		kali.vm.box_check_update = false 

		kali.vm.synced_folder ".\\shared\\jasonlws-kali", "/root/jasonlws-kali"

		kali.vm.provision "shell", path: "config/kali-provision.sh"

		kali.vm.provider :virtualbox do |v| 

			v.name = "jasonlws-kali" 
			v.memory = 8192 # 8GB 
			v.cpus = 4 

		end 

	end 
	
	config.vm.define "jasonlws-docker" do |docker|

		docker.vm.hostname = "jasonlws-docker"

		docker.vm.box = "generic/ubuntu2004"

		docker.vm.network "private_network", ip: "192.168.56.111", netmask: "255.255.255.0"

		docker.vm.box_check_update = false 

		docker.vm.synced_folder ".\\shared\\jasonlws-docker", "/root/jasonlws-docker"

		docker.vm.provision "shell", path: "config/docker-provision.sh"

		docker.vm.provider :virtualbox do |v| 

			v.name = "jasonlws-docker" 
			v.memory = 1024 # 1GB 
			v.cpus = 2

		end 
		
	end

end 